-- Create a table to store the app state
CREATE TABLE app_state (
  id INTEGER PRIMARY KEY,
  state_data JSONB NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Insert an initial row
INSERT INTO app_state (id, state_data) VALUES (1, '{}');

-- Set up Row Level Security (RLS)
ALTER TABLE app_state ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows anyone to read and update the state
-- (Since this is a simple app without user auth yet, we allow public access)
CREATE POLICY "Allow public read access" ON app_state FOR SELECT USING (true);
CREATE POLICY "Allow public update access" ON app_state FOR UPDATE USING (true);
CREATE POLICY "Allow public insert access" ON app_state FOR INSERT WITH CHECK (true);

-- Create a table to store dance-level metadata and state
CREATE TABLE IF NOT EXISTS dance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  dancers TEXT[] NOT NULL DEFAULT '{}',
  theme_color TEXT NOT NULL DEFAULT '#a855f7',
  view_mode TEXT NOT NULL DEFAULT 'adult' CHECK (view_mode IN ('adult', 'kid')),
  prompt_lead_ms INTEGER NOT NULL DEFAULT 200 CHECK (prompt_lead_ms >= 0),
  state_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS dance_set_updated_at ON dance;
CREATE TRIGGER dance_set_updated_at
BEFORE UPDATE ON dance
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

ALTER TABLE dance ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access on dance" ON dance;
CREATE POLICY "Allow public read access on dance" ON dance FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert access on dance" ON dance;
CREATE POLICY "Allow public insert access on dance" ON dance FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update access on dance" ON dance;
CREATE POLICY "Allow public update access on dance" ON dance FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete access on dance" ON dance;
CREATE POLICY "Allow public delete access on dance" ON dance FOR DELETE USING (true);
